fix task 10

diff --git a/0x05-processes_and_signals/8-beheaded_process b/0x05-processes_and_signals/8-beheaded_process
--- a/0x05-processes_and_signals/8-beheaded_process
+++ b/0x05-processes_and_signals/8-beheaded_process
@@ -1,3 +1,18 @@
 #!/usr/bin/env bash
 # Kill the '7-highlander' process using pkill
-pkill -f "7-highlander"
+PID=$(pgrep -f "7-highlander")
+
+# Check if the process was found
+if [ -n "$PID" ]; then
+    # Attempt to terminate the process
+    kill "$PID"
+    
+    # Check if the kill command was successful
+    if [ $? -eq 0 ]; then
+        echo "OK"
+    else
+        echo "Failed to stop 7-highlander process."
+    fi
+else
+    echo "7-highlander process not found."
+fi
